import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import Breadcrumbs from "@/components/ui/breadcrumbs/breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SidebarProvider defaultOpen>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 items-center gap-2 border-b px-3">
              <SidebarTrigger />
              <Breadcrumbs />
            </header>
            <main className="flex-1 p-3">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
